### ISSUE TITLE
Compiling hamcrest fails

### ISSUE THREAD

**Issue by kkoci** [esl/escalus#114]
I'm compiling the escalus XMPP client

But everything goes well with rebar3 until it compiles hamcrest, it throws me this error:

`===> Compiling hamcrest
===> Compiling _build/default/lib/hamcrest/src/hamcrest.erl failed
_build/default/lib/hamcrest/src/hamcrest.erl:59: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:63: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:67: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:72: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:79: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:90: syntax error before: '/'
_build/default/lib/hamcrest/src/hamcrest.erl:108: syntax error before: '/'`

Any ideas about this?

Thanks in advance!

**Comment by michalwski** [comment]
Hi @kkoci, what Erlang/OTP version do you use?

**Comment by mischka** [comment]
may update the deps to hamcrest 0.1.3

**Comment by erszcz** [comment]
Not a problem at least as of e7b3c87. Probably as of bb2d0bf0eb1115e7d277e7b2250cf37dcb72b8cb, which switched the WebSocket client from `wsecli` to `gun`. Please reopen if the problem remains.
