### ISSUE TITLE
Escalus basic example issue

### ISSUE THREAD

**Issue by hamdijmii1992** [esl/escalus#130]
OTP: 19

I tried to follow escalus quick start tuto to run a basic example, but I got an error after executing this erlang line.

`{ok, Carol, _, _} = escalus_connection:start(CarolSpec).
** exception error: undefined function bosh:connect/1
     in function  escalus_connection:connect/1 (src/escalus_connection.erl, line 144)
     in call from escalus_connection:start/2 (src/escalus_connection.erl, line 103)
`

**Comment by michalwski** [comment]
Thanks for rising the issue. There is a bug in the priv/escalus.config file in line 20. You can change `bosh` to `escalus_bosh`. This should work. There is also another bug in line 37. There should be `escalus_ws` instead of just `ws`.

Could you also open a PR with this fix?

**Comment by hamdijmii1992** [comment]
@michalwski Thank you, The last error disappeared but I got another error:

`{ok, Caroll, _, _} = escalus_connection:start(CarolSpec).
** exception error: no match of right hand side value {error,{connection_step_failed,{{escalus_session,authenticate},
                                                                                      {client,undefined,escalus_bosh,
                                                                                              {<0.157.0>,<<"/http-bind">>},
                                                                                              false,false,<0.156.0>,undefined},
                                                                                      [{username,<<"carol">>},
                                                                                       {server,<<"localhost">>},
                                                                                       {host,<<"localhost">>},
                                                                                       {port,5280},
                                                                                       {auth,{escalus_auth,auth_plain}},
                                                                                       {wspath,undefined},
                                                                                       {username,<<"carol">>},
                                                                                       {server,<<"localhost">>},
                                                                                       {password,<<"jinglebells">>},
                                                                                       {transport,escalus_bosh},
                                                                                       {path,<<"/http-bind">>},
                                                                                       {port,5280}],
                                                                                      [{compression,false},
                                                                                       {starttls,false},
                                                                                       {stream_management,true},
                                                                                       {advanced_message_processing,false},
                                                                                       {client_state_indication,false},
                                                                                       {sasl_mechanisms,[<<"X-OAUTH">>,<<"DIGEST-MD5">>,
                                                                                                         <<"SCRAM-SHA-1">>,<<"PLAIN">>]},
                                                                                       {caps,undefined}]},
                                                                                     {auth_failed,<<"carol">>,
                                                                                                  {xmlel,<<"failure">>,
                                                                                                         [{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],
                                                                                                         [{xmlel,<<"internal-error">>,[],[]}]}}}}`

Can you please help me ?

**Comment by hamdijmii1992** [comment]
For the last error, it's from me because I missed to create xmpp users (carol and alice ...)

**Comment by hamdijmii1992** [comment]
#130
